### ISSUE TITLE
Minor Bug in rare case that files end up on two different drives

### ISSUE THREAD

**Issue by Gerdofal** [eyeonus/Trade-Dangerous#105] opened 2022-12-26 16:57 UTC
I encountered this doing my initial import, when a file in a temp folder (on drive C) was to be moved to my data folder (on drive D).  The Python os.rename function cannot "rename" a file onto a different drive. I got the error:

OSError: [WinError 17] The system cannot move the file to a different disk drive

Can be fixed by copying the file from temp to the new location, then deleting the temp file, instead of renaming. The workaround I used was to update my environment variable to put my data folder on C.

**Comment by eyeonus** [comment] 2022-12-26 21:09
Obviously issues with Python need to be addressed by the python development staff.

**Closed by eyeonus** 2022-12-26 21:09 UTC
Labels: wontfix

**Comment by Gerdofal** [comment] 2022-12-26 21:16
It is not an issue with Python. The issue is that the rename command is not intended to actually move files, just rename them. Windows OS only allows renames to impact one drive. The correct code to use in this case is either dual commands (a copy, a verify, and then a delete) or one of a number of libraries that have a true move command.

**Comment by eyeonus** [comment] 2022-12-27 01:37
Since TD does not rename any files, the problem does not originate with TD.

**Comment by Gerdofal** [comment] 2022-12-27 01:45
I found renames at:
transfers.py line 223 and 226
eddblink_plug.py line 997
cache.py line 956
update_cmd.py line 142

Unfortunately I did not take notes on which exact one had the issue. It wasn't obvious, probably burried somewhere in the trace. I'll be happy to kill my install and reinstall again with the non-working settings if you think it would help to know which one?  It happened during my initial download via eddblink and my hunch is that it might be eddblink_plug.py but I'll be happy to look if that would help.

**Comment by eyeonus** [comment] 2022-12-27 02:02
None of the instances of TD renaming a file move the file from the directory it is in before the rename, because, as already mentioned, TD does not use the rename command to move files.

> Unfortunately I did not take notes on which exact one had the issue. It wasn't obvious, probably burried somewhere in the trace. I'll be happy to kill my install and reinstall again with the non-working settings if you think it would help to know which one? It happened during my initial download via eddblink and my hunch is that it might be eddblink_plug.py but I'll be happy to look if that would help.

Without knowing the steps that reproduce the error, I cannot identify or fix it.
